#! /bin/sh
#
# skeleton	example file to build /etc/init.d/ scripts.
#		This file should be used to construct scripts for /etc/init.d.
#
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian GNU/Linux
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#
# Version:	@(#)skeleton  1.8  03-Mar-1998  miquels@cistron.nl
#
# This file was automatically customized by dh-make on Mon, 22 Apr 2002 16:15:28 +0300

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/var/www/vhcs2/daemon/vhcs2_daemon
NAME=vhcs2_daemon
DESC=vhcs2_daemon

PIDFILE=`grep -i 'pidfile' /etc/vhcs2/vhcs2.conf | sed -e 's/pidfile[\t ]\+//i'`
if [ "x$PIDFILE" = "x" ];
then
        PIDFILE=/var/run/vhcs2daemon.pid
fi

test -f $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --verbose  --exec $DAEMON -- -p $PIDFILE
	 /etc/init.d/vhcs2_network
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --verbose --pidfile $PIDFILE --exec $DAEMON
        rm $PIDFILE
	echo "$NAME."
	;;
  restart|force-reload)
	echo "Restarting $DESC: "                                      
	start-stop-daemon --stop --verbose --pidfile $PIDFILE --exec $DAEMON
	rm $PIDFILE
	start-stop-daemon --start --verbose --exec $DAEMON -- -p $PIDFILE
	/etc/init.d/vhcs2_network
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
